apiVersion: v1
kind: Secret
metadata:
  name: blog-secrets
  namespace: blog-system
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3M= #base64 of rootpass
  wordpress-db-password: d29yZHByZXNz #base64 of wordpress
