apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: blog-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          ports:
            - containerPort: 80
          env: 
            - name: WORDPRESS_DB_HOST
              valueFrom: 
                configMapKeyRef:
                  name: wordpress-config
                  key: db_host
            - name: WORDPRESS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: wordpress-config
                  key: db_name
            - name: WORDPRESS_DB_USER
              value: wordpress
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: wordpress-db-password
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: blog-system
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: wordpress
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress-hpa
  namespace: blog-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
